services:
  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    restart: unless-stopped
    volumes:
      - ../:/workspaces
      - mongodb_data:/data/db
      - ../seed:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

volumes:
  mongodb_data: